apiVersion: v1
entries:
  ah-app:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2023-07-09T22:50:13.959166325-07:00"
    description: A Helm chart for Kubernetes
    digest: eecf1a4dbdab0dd32107be7addca626ea347c40a76b6a5cc760c127593b73b48
    name: ah-app
    type: application
    urls:
    - ah-app-0.1.0.tgz
    version: 0.1.0
  foresightd-mlflow:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-07-09T22:50:13.962875591-07:00"
    dependencies:
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 9.3.4
    description: A Helm chart for deploying mlflow
    digest: f60c81b19c5f7678ef9cdda22a2b96b80fd50d2446b5bc4cbd4cbd2b258f9ca0
    name: foresightd-mlflow
    type: application
    urls:
    - foresightd-mlflow-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-07-09T22:50:13.959455892-07:00"
    description: A Helm chart for deploying mlflow
    digest: f595c9079239f0f16bec98859242fffe8c8bf086156c7ffb9c2cdfe3a821d2b9
    name: foresightd-mlflow
    type: application
    urls:
    - foresightd-mlflow-0.0.1.tgz
    version: 0.0.1
generated: "2023-07-09T22:50:13.958577094-07:00"
